### ISSUE TITLE
Allow SSL certificates to be somewhere else than /etc/ssl/certs/

### ISSUE THREAD

**Issue by wynksaiddestroy** [capistrano-plugins/capistrano-unicorn-nginx#100]
I'm using Let's Encrypt to create my SSL certificates. When using the recommended method by running [Certbot](https://certbot.eff.org) the certificates are placed in `/etc/letsencrypt/live/www.foobar.me/` for example.

Unfortunately the options `:nginx_ssl_cert`and `:nginx_ssl_cert_key` will only accept filenames that are relative to `/etc/ssl/certs/` and `/etc/ssl/private/`.

Wouldn't it be useful to accept absolute paths and filenames in equal measure?

**Comment by wynksaiddestroy** [comment]
While browsing the source code I've found the two (undocumented) options `:nginx_ssl_cert_path` and `:nginx_ssl_cert_path` which solved my problem.

Should I add these to the [full options list on the wiki page](https://github.com/capistrano-plugins/capistrano-unicorn-nginx/wiki/Template-customization)?

**Comment by wynksaiddestroy** [comment]
I've updated the options wiki page. Have a look at: https://github.com/wynksaiddestroy/capistrano-unicorn-nginx-wiki/blob/master/Configuration.md

**Comment by wynksaiddestroy** [comment]
If you have a minute to spare could you please have a look this issue, @griffithac? I’d like to clean up my repositories. Thanks in advance.

**Comment by griffithac** [comment]
@wynksaiddestroy your updates to the wiki have been added.  Unfortunately pull requests for wikis are kind of a pain to setup, so you just copied your changes in manually.  Thanks for your work on this.  It is much more complete now and easier to make sense of.
