### ISSUE TITLE
HOME variable not set in unicorn init script

### ISSUE THREAD

**Issue by rhomeister** [capistrano-plugins/capistrano-unicorn-nginx#12]
I'm using capistrano-unicorn-nginx in combination with https://github.com/rvm/rvm1-capistrano3. The problem I'm experiencing is that when I execute `cap [env] unicorn:start` I get the following error `Can not find rvm in '/.rvm'.` 

See https://github.com/rvm/rvm1-capistrano3/issues/43 for a full discussion. The problem seems to be that the $HOME variable in the init script is blank at the start of the script. 

One solution I came up with is to change https://github.com/bruno-/capistrano-unicorn-nginx/blob/master/lib/generators/capistrano/unicorn_nginx/templates/unicorn_init.erb#L18 to something like:

`CMD="cd $APP_ROOT && HOME=/home/<%= fetch(:user) %> <%= bundle_unicorn("-D -c", fetch(:unicorn_config), "-E", fetch(:stage)) %>"`

Not sure if this is the right way to do this, but I don't know if there is another way to get the HOME variable in this init script.

FYI: I'm using the Ubuntu 14.04 x64 image from DigitalOcean.

**Comment by genericlady** [comment]
For me I had to change $AS_USER to $USER to get it to work even though in the init script $AS_USER is assigned the same name as the environment variable $USER.
