### ISSUE TITLE
SPDY patch on nginx?

### ISSUE THREAD

**Issue by marvindanig** [capistrano-plugins/capistrano-unicorn-nginx#30]
Is there a way to include SPDY patch on nginx installation?

**Comment by marvindanig** [comment]
:+1: awesome, giving it a try today :)

**Comment by rhomeister** [comment]
@bruno- I've added an option to enable spdy on nginx. For details see http://nginx.org/en/docs/http/ngx_http_spdy_module.html. I will write documentation for this feature when the PR has been merged.

@marvindanig this only works if you have the correct version of nginx and openssl installed. (OpenSSL version 1.0.0d or higher). Hope this helps ;)

**Comment by bruno-** [comment]
@rhomeister, merged and new gem version `v3.2.0` is out.
