### ISSUE TITLE
nginx servername alias

### ISSUE THREAD

**Issue by luckyraul** [capistrano-plugins/capistrano-unicorn-nginx#42]
provide support for it

**Comment by bruno-** [comment]
Hi,
I'm not all too familiar with this feature, but I \*think* it would be possible by manually editing `nginx_conf` template.
You can read instructions about generating and working with templates in [this wiki page](https://github.com/capistrano-plugins/capistrano-unicorn-nginx/wiki/Template-customization).

As mentioned above, I think this should enable you to elegantly handle the requirement so I'll close the issue. Please, feel free to reopen if it doesn't do the trick or you have more questions.

**Comment by luckyraul** [comment]
http://nginx.org/en/docs/http/ngx_http_core_module.html#server_name

Can you make setting with array of additional servername for application?
