### ISSUE TITLE
nginx reload not working (stuck after entering sudo password)

### ISSUE THREAD

**Issue by navjeetc** [capistrano-plugins/capistrano-unicorn-nginx#43]
I am running "cap staging nginx:reload" cap task and it prompts me to enter sudo password, but nothing happens after I type password. It's just stuck there. 
I am using capistrano-unicorn-nginx plugin v 3.1.2

**Comment by bruno-** [comment]
Hey, I think the issue might be with capistrano running without pty. The solution is likely in enabling passwordless sudo for your deployer user (at least this is what I have always enabled and do all the testing etc).

Capistrano docs recommend doing that for scripts outside the core capistrano [read here](http://capistranorb.com/documentation/getting-started/authentication-and-authorisation/#authorisation).

Let us know if that solved it?

**Comment by navjeetc** [comment]
Enabling passwordless sudo for deployer user fixed the issue. Thanks.
