### ISSUE TITLE
No such process for unicorn restart

### ISSUE THREAD

**Issue by CArayson1223** [capistrano-plugins/capistrano-unicorn-nginx#58]
Hi,

I faced this issues after I done with my cap production setup & run cap production deploy. 

No ideas why no such process for restart.
Did anyone faced this before?

```
[8984bdeb] Command: /usr/bin/env service unicorn_AppName_production restart
DEBUG [8984bdeb] 	/etc/init.d/unicorn_AppName_production: line 26: kill: (6763) - No such process
DEBUG [8984bdeb] 	Couldn't reload, starting 'export HOME; true /home/ubuntu ; cd /home/ubuntu/AppName/current && ~/.rvm/bin/rvm default do bundle exec unicorn -D -c /home/ubuntu/AppName/shared/config/unicorn.rb -E production' instead
DEBUG [8984bdeb] 	master failed to start, check stderr log for details
```

**Comment by iam1492** [comment]
I have same issue. @CArayson1223 did you solve this issue?

**Comment by CArayson1223** [comment]
@iam1492 Ya. I did solve this errors. Is because of there are some errors produce in your applications. go to your app deploy folders under shared/log/unicorn.stderr.log or deployment.log, check any applications produce errors during the app deployment. Once you solve it then should be alright if I remember correctly. Hopefully this help you out. =D.
